### PR TITLE
Share db connection for API integration tests

### PR DESCRIPTION
**Pull request by jmeas**
I should prob move this to a separate file tbqh

Solves #304

### CODE REVIEW

**Comment by jmeas** [comment]
I can just use the existing DB service for this

**Comment by jmeas** [comment]
Gonna merge as-is so I can access the `pgp` var to `end` within `afterEach`.

**Comment by vitaly-t** [comment]
You have access to `pgp` object from the `db` object, see [$config](http://vitaly-t.github.io/pg-promise/Database.html#.$config).

To terminate the library, you can do: `db.$config.pgp.end()` ;)

**Comment by jmeas** [comment]
ya da boooomb @vitaly-t

**Pull request merged**
